### ISSUE TITLE
[Meta] Improve SEO

### ISSUE THREAD

**Issue by celiacheff** [tchapgouv/tchap-landing-page#125]
Partie purement CSR
- [ ] Création d'un sitemap.xml
- [ ] Ajout d'un robot.txt
- [ ] Remplacer les balises div par des p
- [ ] Ajout/remplacement de balises h1/h2

Partie nécessitant du SSR
- [ ] Ajout des urls canoniques
- [ ] Ajout de balises meta dynamiques
- [ ] Intégrer les balises Opengraph

**Comment by celiacheff** [comment]
A noter que React n'est pas le plus adapté pour du SEO, migrer vers Next, Remix etc... pourrait être un choix judicieux.
Sinon, quelques hacks pourraient faire l'affaire, comme utiliser react-helmet + static-site-generator-webpack-plugin.
