### ISSUE TITLE
Migrer la landing page sur Sites Faciles

### ISSUE THREAD

**Issue by areox-net** [tchapgouv/tchap-landing-page#181]
On souhiate faire une refonte de landing page en utilisant un CMS qui permette de faire de la maintenance à des membres de l'équipe non-codeurs.

Suite à une enquête au près de la communauté Beta, l'outil Wagtail nous a été conseillé par Fabien Le Frapper  https://github.com/betagouv/content-manager:

_C'est pas totalement no code mais c'est bien fait.Iil y a besoin d'un peu de code pour le setup, car les modèles de page doivent être écrits en python. Uune fois en place, l'éditeur (Streamfield) est très simple d'utilisation et les éditeurs pourront maintenir une (ou plusieurs..) landing sans problème_ 

A tester.
```[tasklist]
### Tasks
- [x] Déployer sur scalingo
- [ ] Changer le DNS vers tchap.beta.gouv.fr (une fois que le site sera prêt)
- [ ] https://github.com/tchapgouv/tchap-design/issues/12
- [ ] Relier avec Matomo
- [x] Créer un doc notion pour la prise en main de l'outil https://www.notion.so/mercurial-timer-ec4/Landing-page-avec-site-facile-bca52cf3a01e4bdd8e362694feb96e9e
- [ ] https://github.com/tchapgouv/tchap-infra/issues/2860
```

**Comment by areox-net** [comment]
Ici une vidéo qui montre comment marche Wagtail https://www.youtube.com/watch?v=N7W_EXX2aZ0

**Comment by areox-net** [comment]
Un exemple de site fait avec ce content-manager https://conseil-refondation.fr/

**Comment by areox-net** [comment]
@Raphaelrobert65 @odelcroi ici le ticket initial sur le sujet CMS

**Comment by areox-net** [comment]
@MarcWadai

**Comment by Raphaelrobert65** [comment]
Piste : https://sites-faciles.beta.numerique.gouv.fr/

**Comment by odelcroi** [comment]
notes sur site facile : 
## opérateur Wagtail
- wagtail basé sur django
- basé sur scalingo
- page d'admin
- wordpress-like : avec des blocs
- fils d'ariane
- check d'accessibilité


Questions : 
- design évolué : modifier le css? oui : dans django 
- qui l'utilise chez Beta : programme 10%, CNR, campus du numérique sur outline
- Salon Tchap : Content Manager

**Comment by areox-net** [comment]
Ici le draft in progress https://tchap-landing-v2.osc-secnum-fr1.scalingo.io

**Comment by Raphaelrobert65** [comment]
Besoin supplémentaire : ajouter une page **Budget** comme ça sur notre site : https://betagouv.github.io/template-nextjs/budget
